### ISSUE TITLE
Release tarball and VCS v4.6.2 tag are very different

### ISSUE THREAD

**Issue by jekhor** [andy-shev/LogJam#1]
4.6.2 release tarball and VCS snapshot https://github.com/andy-shev/LogJam/zipball/v4.6.2 are very different:

$ diff -Nru andy-shev-LogJam-14481ad/  logjam-4.6.2-upstream/ | diffstat | wc -l
128

Many of those files are not autogenerated.

**Comment by andy-shev** [comment]
Seems no further comments, assume it's solved.
